### ISSUE TITLE
Do not use pickle to store parsed articles

### ISSUE THREAD

**Issue by jankrepl** [BlueBrain/Search#422]
The PR #412 introduced (among other things) a parsing logic (`bbs_database parse`) that ends up writing a pickle file.

However, this is not optimal. A  few reasons:
* Security risk since there is code execution when loading (we even explicitly ignore the `bandit` warning)
* If the `Article` source code changes we might not be able to load existing pickle files

We should look for alternatives.

**Comment by Stannislav** [comment]
Since it's plain text we could think about JSON. Maybe also [`msgpack`](https://pypi.org/project/msgpack)

**Comment by FrancescoCasalegno** [comment]
Maybe I am missing other solutions, but I have the impression that the only options are the following.

1. **Keep using `pickle`.**
   Dangerous. `bandit` warns against it because loading `pickle`s  may lead to arbitrary code execution.
2. **Find a safe drop-in alternative to `pickle`.**
   Personally I do know any, but I would be more than happy if someone finds one.
3. **Work on a custom format for dumping and loading parsed files.**
   Sounds really bad to me. First, it would require lots of efforts to implement and maintain. Second, it would imply somehow re-implementing the JSON/XML format, so it's not clear to me in this case what's the advantage of introducing this complicated overhead in order to split `add` from `parse`.
4. **Merge `add` and `parse` functionalities.**
   Unless there are strong arguments against this, or a better solution is found (e.g. option 2. above) then I think this should be considered.
   
What do you guys think about it?
