### ISSUE TITLE
Harmonize download from different sources when `--from_month` is before the storage change date

### ISSUE THREAD

**Issue by EmilieDel** [BlueBrain/Search#528]
## Description

It seems that every source has changed its structure of file at a given time. Currently, we raise a warning for `arxiv` and return 1 in the CLI. It could be nice to harmonize this behaviour to all the sources.

**Comment by FrancescoCasalegno** [comment]
Most online literature archives have changed the way they store their articles, so that downloading articles published after a certain date (i.e. the option --from-month in bbs_database download) is easy if that date is after the time they implemented a change in the structure of the storage.

But what if the --from-month is before that time?
If --source=arxiv then we decided to return 1 and log an error. But for the other sources we don't have such control.

The goal of this issue is to harmonize the behavior of all sources, to return 1 and log an error if the --from_month is before the date when they changed the structure of their storage.
